Update action.yml

diff --git a/.github/actions/create-release/action.yml b/.github/actions/create-release/action.yml
--- a/.github/actions/create-release/action.yml
+++ b/.github/actions/create-release/action.yml
@@ -7,14 +7,29 @@ runs:
     - name: Set Tag Name
       shell: bash
       if: startsWith(github.ref, 'refs/tags/')
-      # trim prefix from ref to get tag name
-      run: echo "TAG_NAME=${GITHUB_REF#'refs/tags/'}" >> ${GITHUB_ENV}
+      run: |
+        echo "TAG_NAME=${GITHUB_REF#'refs/tags/'}" >> ${GITHUB_ENV}
+
+    - name: Set ZIP Name
+      shell: bash
+      if: startsWith(github.ref, 'refs/tags/')
+      run: |
+        echo "ZIP_NAME=${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}" >> ${GITHUB_ENV}
 
     - name: Add tag to folder name
       shell: bash
       if: startsWith(github.ref, 'refs/tags/')
       run: |
         mv ${{ env.ZIP_NAME }} ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}
+
+    - name: Check if ZIP file exists
+      run: |
+        if [ ! -f "${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}.zip" ]; then
+          echo "ZIP file not found!"
+          exit 1
+        else
+          echo "ZIP file exists!"
+        fi
 
     - name: Archive Release
       uses: thedoctor0/zip-release@master
@@ -34,5 +49,4 @@ runs:
       uses: softprops/action-gh-release@master
       if: startsWith(github.ref, 'refs/tags/')
       with:
-        files: |
-          ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}.zip
+        files: ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}.zip
